# This is a basic workflow to help you get started with Actions

name: jest-code-coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs
      - name: Node Installieren und Bauen
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn add react-scripts
      - run: react-scripts test --watchAll --coverage --useStderr=false --forceExit
        env:
             CI: false
      
      
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            # Directory to search for coverage reports.
            directory: coverage
 

  
