name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run test:ci
      - run: yarn run build
        env:
          REACT_APP_NODE_ENV: production
          REACT_APP_AWS_REGION: nope
          REACT_APP_AWS_USER_POOL_ID: nope
          REACT_APP_AWS_APP_CLIENT_ID: nope
          REACT_APP_COMMIT_HASH: ${{ github.sha }}
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/cobertura-coverage.xml
          flags: unittests # optional
          name: codecov-umbrella # optional

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test-and-build]
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hft-crap-stories-react"
          heroku_email: "mathias.maciossek@gmail.com"
          buildpack: "https://github.com/mars/create-react-app-buildpack"
